set BARGAINCAVE_HOME=%~dp0
set PYTHONPATH=%BARGAINCAVE_HOME%;%PYTHONPATH%
set PYTHONPATH=%BARGAINCAVE_HOME%\warehouse\common\;%PYTHONPATH%

set ENV=dev
set PIPENV_IGNORE_VIRTUALENVS=1

call %BARGAINCAVE_HOME%\.secret.env
