/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://pd6glgjfnrdv5n2etzvlxfxgye.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7esmhpkx65gajea2sa22oapvhu",
    "aws_cloud_logic_custom": [
        {
            "name": "warehouseapi",
            "endpoint": "https://3u2yuqwjej.execute-api.eu-west-2.amazonaws.com/staging",
            "region": "eu-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-2:2ee9558e-23c5-411d-9b8a-099603e8e1cf",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_zvyfxrk5t",
    "aws_user_pools_web_client_id": "2k5uqgd3qumercij1sdr2l94j7",
    "oauth": {},
    "aws_user_files_s3_bucket": "bargaincave-photos142503-staging",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
