on: workflow_dispatch

jobs:
 build_apk_aab:
   name: Build debug artifacts
   runs-on: ubuntu-20.04
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with: {java-version: 1.8}
     - name: Build debug APK
       run: |
          ls -al
#         gradlew assembleDebug
       working-directory: ./warehouse
