on: workflow_dispatch

jobs:
 build_apk_aab:
   name: Build debug APK
   runs-on: ubuntu-20.04
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with: {java-version: 11}
     - name: Install Amplify CLI
       run: |
          sudo npm install -g @aws-amplify/cli --unsafe-perm=true
     - name: Build debug APK
       run: |
          chmod +x gradlew
          ./gradlew assembleDebug
       working-directory: ./warehouse
     - name: Upload APK
       uses: actions/upload-artifact@v2
       with:
         name: app-debug.apk
         path: warehouse/app/build/outputs/apk/debug/app-debug.apk
